import { theme } from 'antd'
import type { ThemeConfig } from 'antd'

export const dashboardTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  cssVar: { prefix: 'live-ops' },
  hashed: true,
  token: {
    colorBgBase: '#F7F6F2',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#F7F6F2',
    colorPrimary: '#171716',
    colorPrimaryHover: '#34322F',
    colorPrimaryActive: '#0D0D0C',
    colorInfo: '#4565D4',
    colorSuccess: '#1E7A54',
    colorWarning: '#9B5F0E',
    colorError: '#B83C3C',
    colorText: '#171716',
    colorTextSecondary: '#5F5C56',
    colorTextTertiary: '#706D67',
    colorTextQuaternary: '#706D67',
    colorBorder: '#8D8981',
    colorBorderSecondary: '#ECE8E1',
    colorFill: '#F3F1EC',
    colorFillSecondary: '#F8F7F3',
    colorFillTertiary: '#FAF9F6',
    colorFillQuaternary: '#FBFAF7',
    borderRadius: 12,
    borderRadiusSM: 8,
    borderRadiusLG: 16,
    controlHeight: 38,
    controlHeightSM: 32,
    fontFamily: 'Inter, "SF Pro Display", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif',
    fontFamilyCode: '"JetBrains Mono", "SFMono-Regular", Consolas, monospace',
    fontSize: 14,
    lineWidth: 1,
    motionDurationFast: '0.12s',
    motionDurationMid: '0.18s',
    motionDurationSlow: '0.26s',
    wireframe: false,
    boxShadow: '0 1px 2px rgba(35,31,24,.03), 0 8px 24px rgba(35,31,24,.05)',
    boxShadowSecondary: '0 20px 60px rgba(35,31,24,.14)',
  },
  components: {
    Layout: {
      bodyBg: '#F7F6F2',
      headerBg: 'rgba(255,255,255,.9)',
      siderBg: '#FBFAF7',
      triggerBg: '#F3F1EC',
    },
    Menu: {
      itemBg: 'transparent',
      itemColor: '#5F5C56',
      itemHoverBg: '#F3F1EC',
      itemHoverColor: '#171716',
      itemSelectedBg: 'rgba(196,71,32,.10)',
      itemSelectedColor: '#171716',
      groupTitleColor: '#706D67',
      itemBorderRadius: 10,
      itemHeight: 42,
      iconSize: 18,
    },
    Card: {
      headerBg: 'transparent',
      colorBorderSecondary: '#ECE8E1',
    },
    Table: {
      headerBg: '#F8F7F3',
      headerColor: '#5F5C56',
      rowHoverBg: '#FAF8F4',
      borderColor: '#ECE8E1',
      headerSortActiveBg: '#F3F1EC',
      headerSortHoverBg: '#F3F1EC',
      fixedHeaderSortActiveBg: '#F3F1EC',
    },
    Button: {
      defaultBg: '#FFFFFF',
      defaultBorderColor: '#8D8981',
      defaultColor: '#171716',
      defaultHoverBg: '#FAF8F4',
      primaryShadow: 'none',
      dangerShadow: 'none',
    },
    Segmented: {
      trackBg: '#F3F1EC',
      itemSelectedBg: '#171716',
      itemSelectedColor: '#FFFFFF',
      itemHoverBg: '#F8F7F3',
    },
    Tabs: {
      itemColor: '#5F5C56',
      itemHoverColor: '#B83F1B',
      itemSelectedColor: '#171716',
      inkBarColor: '#C44720',
    },
    Drawer: {
      colorBgElevated: '#FFFFFF',
    },
    Modal: {
      contentBg: '#FFFFFF',
      headerBg: '#FFFFFF',
    },
    Tooltip: {
      colorBgSpotlight: '#FFFFFF',
      colorTextLightSolid: '#171716',
    },
    Progress: {
      defaultColor: '#4565D4',
      remainingColor: '#ECE8E1',
    },
    Switch: {
      colorPrimary: '#C44720',
      colorPrimaryHover: '#B83F1B',
    },
  },
}
